#### 1、导入numpy

In [1]:
import numpy as np

#### 2、生成numpy数组

In [5]:
x=np.array([1.0,2.0,3.0])
x

array([1., 2., 3.])

In [6]:
type(x)

numpy.ndarray

#### 3、算术运算

In [7]:
#进行运算的两个数组的元素个数必须相同
x=np.array([1.0,2.0,3.0])
y=np.array([2.0,4.0,6.0])
x+y

array([3., 6., 9.])

In [8]:
x-y

array([-1., -2., -3.])

In [9]:
x*y #对应元素相乘

array([ 2.,  8., 18.])

In [10]:
x/y #对应元素相除

array([0.5, 0.5, 0.5])

In [11]:
x/2.0

array([0.5, 1. , 1.5])

#### 4、N维数组

In [12]:
A=np.array([[1,2],[3,4]]) #生成一个2 × 2的矩阵A
A

array([[1, 2],
       [3, 4]])

In [13]:
A.shape

(2, 2)

In [14]:
A.dtype

dtype('int64')

In [15]:
B=np.array([[3,0],[0,6]])
A+B

array([[ 4,  2],
       [ 3, 10]])

In [16]:
A*B

array([[ 3,  0],
       [ 0, 24]])

In [17]:
A*10

array([[10, 20],
       [30, 40]])

数学上将一维数组称为`向量`，将二维数组称为`矩阵`。

可以将一般化之后的向量或矩阵等统称为`张量（tensor）`。
本书基本上将二维数组称为`矩阵`，将三维数组及三维以上的数组称为`张量`或`多维数组`。

#### 5、广播

NumPy中，形状不同的数组之间也可以进行运算。  
A*10中，NumPy中，形状不同的数组之间也可以进行运算。  
这个巧妙的功能称为`广播（broadcast）`。
![jupyter](./imgs/1_5_5_broadcast.png)

In [19]:
A = np.array([[1, 2], [3, 4]])
B = np.array([10, 20])
A*B

array([[10, 40],
       [30, 80]])

![jupyter](./imgs/1_5_5_broadcast2.png)

#### 6、访问元素

方法2:索引操作

In [21]:
X=np.array([[51,55],[14,19],[0,4]])
X

array([[51, 55],
       [14, 19],
       [ 0,  4]])

In [22]:
X[0]

array([51, 55])

In [23]:
X[0][1]

55

In [24]:
for row in X:
    print(row)

[51 55]
[14 19]
[0 4]


方法2:NumPy还可以使用数组访问各个元素

In [26]:
X=X.flatten() #将X转换为一维数组
X

array([51, 55, 14, 19,  0,  4])

In [28]:
X[np.array([0, 2, 4])] #获取索引为0、 2、 4的元素

array([51, 14,  0])

In [29]:
X>15 #判断X中元素是否大于15，返回bool数组

array([ True,  True, False,  True, False, False])

In [30]:
X[X>15] #X中大于15的元素

array([51, 55, 19])

NumPy中，主要的处理也都是通过C或C++实现的。  
因此，我们可以在不损失性能的情况下，使用Python便利的语法。 